# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='forwardStrips',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=20)),
                ('twelve', models.DecimalField(decimal_places=3, max_digits=4)),
                ('twentyFour', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
    ]
