# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_forwardstrips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basisfutures',
            name='Open',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='basisfutures',
            name='settle',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='gasfutures',
            name='Open',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='gasfutures',
            name='settle',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
