# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_auto_20160711_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasstorage',
            old_name='stock',
            new_name='fiveYearAvgBcf',
        ),
        migrations.AddField(
            model_name='gasstorage',
            name='lastWeekBcf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gasstorage',
            name='product',
            field=models.TextField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasstorage',
            name='summary',
            field=models.TextField(default='default', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasstorage',
            name='thisWeekBcf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gasstorage',
            name='yearAgoBcf',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basisfutures',
            name='settle',
            field=models.TextField(max_length=5),
        ),
        migrations.AlterField(
            model_name='gasfutures',
            name='settle',
            field=models.TextField(max_length=5),
        ),
    ]
