# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_auto_20161003_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasstorage',
            old_name='product',
            new_name='source',
        ),
    ]
